### ISSUE TITLE
Bar-code reader support

### ISSUE THREAD

**Issue by mrajayp** [onaio/tally-ho#152]
The system to additionally support the use of barcode readers to read the barcodes on the forms. The form details are returned and either confirmed or rejected. If rejected the user can try again or type the numbers though the current mechanism. 

Usage available at all phases.

**Comment by pld** [comment]
To the webapp a bar code reader read looks like a single alpha-num string appearing.

Suggest also doing some web search research around ways to simulate (so we can add a test) for a barcode reader read

**Comment by mberg** [comment]
Barcode readers usually just read and sends the text value of the barcode
to a form element.  That's how they work generally when interacting with a
website.  It's similar to a keyboard input.

**Comment by JohnMwashuma** [comment]
Going to research on python/js libraries that support retrieving barcode values from a barcode scanner.

**Comment by pld** [comment]
what'll happen is after the barcode reader reads a barcode it inserts the string from the barcode into whatever element is highlighted

so from the JS perspective, it'll look like a string of numeric text was inserted, this seems like what you can do, https://stackoverflow.com/questions/11290898/detect-when-input-box-filled-by-keyboard-and-when-by-barcode-scanner, detect no key events are fired and assume barcode insert then

i.e.

you know how currently there are two text fields for entering barcode? we want to change that so initially it will show:

* a single text field, but no text can be entered in this field, only the field can be selected (there's a way in JS to do this)
* a text description saying "Scan barcode to proceed"
* a button below it saying "Enter barcode manually"
  * if they click this button it now shows the current two entry text field system (like in case the barcode reader is broken or not available at a station)
  * and there's a button for "Use barcode reader" that toggles back to the other screen

**Comment by JohnMwashuma** [comment]
@pld Thanks this is clear now.
