### ISSUE TITLE
Updating Centres/Station Information

### ISSUE THREAD

**Issue by pld** [onaio/tally-ho#181]
Status: The functionality to adjust the list and details with a GUI and to replace existing files with an upload tool is required

It should be possible to edit, remove or add to the list of races, centers, stations and forms using a GUI. It should also be possible to add or change the number of people registered at a station which may be used in a quarantine trigger. It will be possible to upload new key files to replace existing files for stations, centers and barcodes. The center list with all details should also be downloadable in CSV format.

**Comment by JohnMwashuma** [comment]
Am breaking down this issue to small executable issues.

**Comment by pld** [comment]
Cool, closing this issue
