### ISSUE TITLE
Marking Race as Available for Release

### ISSUE THREAD

**Issue by pld** [onaio/tally-ho#184]
Super Administrators should be able to apply classifications to entire races. They can be classified as;

* For release
* Not for release

The system will allow the user to add a comment to the race and attach documents. This shall be available for both the data entry software and the National Consolidation/Public website.

**Comment by pld** [comment]
@akahure can you clarify w/them what "adding documents" to this means? There might be more details in the RFP as well. I'd like to cut this part of the feature if possible

**Comment by akahure** [comment]
@pld Okay I have requested more information from Ahmed and Joram.
