### ISSUE TITLE
Attach documents to Races

### ISSUE THREAD

**Issue by akahure** [onaio/tally-ho#201]
The system will allow the user to attach documents to a race. This will be made available for data entry software and the National consolidation/ Public website.

**Comment by akahure** [comment]
comment: what does adding documents entail? what kind of documents, size, process, accessibility..

Response from Ahmed 1:  able to upload photos or PDFs. we can add a ceiling of 10MBs to the size of the upload? 

Response from Ahmed 2: So indeed, this would require the use of a memory stick to be put into the system. It would be done by only people with the respective access. In truth, there are a few instances indeed where people are putting memory sticks into the system - for example to take results off system. It is however sub-optimally. 

An example use case is that there is a station that is cancelled, be a court order. The court order is scanned, and put onto a memory stick. The staff member using the memory stick uploads the scan to the station entry in the system, and marks it as closed.

**Comment by akahure** [comment]
We require to know which users will have this functionality and if it is both Add and Edit. Use cases for this function are important as well

**Comment by pld** [comment]
It's also not clear how this would be available in the public website

**Comment by JohnMwashuma** [comment]
No public website for now. Got this from `HNEC (RMS) Project Update` meeting.

**Comment by JohnMwashuma** [comment]
Issue closed by #218
