### ISSUE TITLE
Add ability to add from a centers list

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#203]
One should be able to create a new center and station from the center list table.

related to #181

**Comment by JohnMwashuma** [comment]
Going to modify the center's and station list table view code to pull center's with station's attached to them and those without. This will prevent creation of duplicate center's which do not have station's attached to them.

**Comment by pld** [comment]
Concluded it's fine not to show centers without stations on that list, since they show up in the centers list when creating a station (even if no stations already exist for them)
