### ISSUE TITLE
Result form processing stats. 

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#251]
### Current requirement functionality
---
*This functionality does not exist in the current software.*
### User Story
---

- [ ] Track how long a form took to pass through the different states (DE1, DE2, etc) and which users did the entry.

- [ ]  Build out tables of users for each group (DE1, DE2, etc), these tables will have the following columns:

   - Username.
   - Number of forms processed per N (hour) by that user.

### Required Changes
---
- [ ] Define a new model for storing result form processing details in each state. Model fields:
   - processing_time
   - result_form: foreign key to result_form model.
   - user: foreign key to user model
   - approved_by_supervisor
   - reviewed_by_supervisor
   - sent_for_review

### Related
---
Issue #243

**Comment by akahure** [comment]
@JohnMwashuma @pld 
I am not sure if we are complicating it but for the requirement I propose the following to track the staff metrics
- Have a filter for the user on the page, if the page shows all the users tied to that tally, we should include a filter that checks 'Role' and 'Username'. Once triggered the page will filter out the specific forms the user or the role has interacted with and the time for processing 
- The inclusion of summaries at the top of the page where it says "Total forms processed" (shown below) here we could include the total forms processed, with the total time taken and the average time per form - depending on the filter triggered (thoughts?)
<img width="997" alt="Screen Shot 2020-03-09 at 15 19 36" src="https://user-images.githubusercontent.com/43808025/76290594-869c8600-62bc-11ea-8774-09445f6a954c.png">

**Comment by JohnMwashuma** [comment]
@akahure This makes sense to me, but the role filter i think should not be there since all the users on this screen will belong to the same role, in this case it's `intake_clerks`. No?

**Comment by pld** [comment]
I agree I don't think we need a filter if this is 1 page per state.

Also, we don't need to show the individual form processing time (we need to record that for calculating, but not show it), only need to show the number of forms and number of forms per hour.

To calculate number of forms per hour per user, for each specific user we sum up the number of forms they processed and divide that number by the sum of time it took for each of their forms, e.g. if it took me 5 hours to process 10 forms, that's 10 / 5 = 2 hour

@akahure @JohnMwashuma is that clear?

**Comment by JohnMwashuma** [comment]
@pld Yes this is clear, i agree.

**Comment by JohnMwashuma** [comment]
Just to be clear @akahure and @pld will we be grouping the forms in terms of the date they were processed so that `forms processed per hour per user` is shown per specific dates?

**Comment by pld** [comment]
Nope, lets do overall for now, that was not in scope. I could see that being useful, but let's leave it as a future thing, do first iteration now w/o no date grouping

@akahure do you think that's clear to client? May need to make sure it's clear by describing how we're planing to do it.

**Comment by JohnMwashuma** [comment]
Cool, thanks.
