### ISSUE TITLE
Track audit supervisor clerks approval rate.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#253]
### Current requirement functionality
---
*This functionality does not exist in the current software.*
### User Story
---

- Per user (supervisor clerk) show supervisor approval rate for forms after ‘Audit’ 
   - Number of forms approved by supervisor / number of forms sent for review to supervisor

### Required Changes
---
 Build out a table for all audit supervisor clerks.

  - supervisor clerk name.
  - number of forms approved.
  - number of forms processed.
  - supervisor approval rate: number of forms approved by supervisor / number of forms sent for review by supervisor.

### Related
---
Issue #243

**Comment by akahure** [comment]
@pld for the below calculation i.e. Supervisor approval rate, should it be 
supervisor approval rate: number of forms approved by supervisor / number of forms sent for review by supervisor.
or 
Number of approved forms (form and note to admin)/ total number of forms received from the Audit team 
![Screenshot - 2020-03-10T105738 059](https://user-images.githubusercontent.com/43808025/76291356-fa8b5e00-62bd-11ea-8eb6-ccefb83c8b90.png)

**Comment by JohnMwashuma** [comment]
@akahure what does this statement `(form and note to admin)` in `Number of approved forms (form and note to admin)/ total number of forms received from the Audit team` mean?

**Comment by akahure** [comment]
> @akahure what does this statement `(form and note to admin)` in `Number of approved forms (form and note to admin)/ total number of forms received from the Audit team` mean?

https://prnt.sc/re2wj7

**Comment by pld** [comment]
@akahure it should be the former:

From the description:

Per user (supervisor clerk) show supervisor approval rate for forms after ‘Audit’
*    Number of forms approved by supervisor / number of forms sent for review to supervisor

The only modification I've made is to change the final 'by' to 'to', is that clear now?

**Comment by JohnMwashuma** [comment]
@pld and @akahure by `number of forms sent for review to supervisor`, this should be the total number of forms the audit team have forwarded to the supervisor for review. Right?

**Comment by pld** [comment]
Well, this is all per user, so:
- group per user
- calculate count of forms sent for review
- calculate count of forms sent for review AND approved
- divided 2nd to last from last, that gives use the "supervisor approval rate" as a ratio

**Comment by JohnMwashuma** [comment]
This is clear
