### ISSUE TITLE
Create a turnout report module

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#273]
### Current requirement functionality
---
*This functionality does not exists in the current software.*
### User Story
---
- Turnout Reports per region, Constituency and sub constituency: This report can be per
region/Constituency/sub constituency, listing: total number of voters in the region, number of voters
voted, turnout percentage, male voters, female voters.

### Implementation plan:
---
#### Turnout Report per Region
- For each `region`, get the `offices` assigned to that particular `region`.
- For each `office`, get `result forms` assigned to that particular `office`.
- For each `result form`, get their `station` using `station number`.
- Group the `result forms` by `station gender` and aggregate `number of registrants`, which will be `number of registrants per office`.
- For each `result form`, get the final `reconciliation form`.
- For each `reconciliation form`, get the `number of ballots used`.
- Aggregate the `number of ballots used`, this will be `number of ballots used per office`.
- Aggregate the `number of ballots used per office`, this will then translate to 1. `number of voters voted` in the `region`, 2.  `male voters or female voters` in the `region` depending on the `Station` gender.
- Aggregate `number of registrants per office` which will translate to `number of voters` in the `region`. 
- The `number of voters` and `number of voters voted` will then be used to calculate the `turnout percentage` in the `region`.

#### Turnout Report per Constituency
- For each `constituency`, get the `centers` assigned to that particular `constituency`.
- For each `center`, get `result forms` assigned to that particular `center`.
- For each `result form`, get their `station` using `station number`.
- Group the `result forms` by `station gender` and aggregate `number of registrants`, which will be `number of registrants per center`.
- For each `result form`, get the final `reconciliation form`.
- For each `reconciliation form`, get the `number of ballots used`.
- Aggregate the `number of ballots used`, this will be `number of ballots used per center`.
- Aggregate the `number of ballots used per center`, this will then translate to 1. `number of voters voted` in the `constituency`, 2.  `male voters or female voters` in the `constituency` depending on the `Station` gender.
- Aggregate `number of registrants per center` which will translate to `number of voters` in the `constituency`. 
- The `number of voters` and `number of voters voted` will then be used to calculate the `turnout percentage` in the `constituency`.

#### Turnout Report per Sub Constituency
- For each `sub constituency`, use the `code` to get `results forms` associated with that `code`.
- For each `result form`, get their `station` using `station number`.
- Group the `result forms` by `station gender` and aggregate `number of registrants`, which will be `number of registrants` in the `sub constituency`.
- For each `result form`, get the final `reconciliation form`.
- For each `reconciliation form`, get the `number of ballots used`.
- Aggregate the `number of ballots used`, this will be `number of ballots used` in the `sub constituency`, this will then translate to 1. `number of voters voted` in the `sub constituency`, 2.  `male voters or female voters` in the `sub constituency` depending on the `Station` gender.
- The `number of registrants` which will translate to `number of voters` in the `sub constituency`.
- The `number of voters` and `number of voters voted` will then be used to calculate the `turnout percentage` in the `sub constituency`.

**Comment by JohnMwashuma** [comment]
### Related to:
https://github.com/onaio/tally-ho/issues/244

**Comment by pld** [comment]
Makes sense, @akahure make sure to check client is clear on what we're building here

**Comment by JohnMwashuma** [comment]
### Updated Implementation plan:
Aggregate `number of ballots used` per `sub constituency`, calculate the expected turnout by dividing  `number of ballots used` by `registants` then build out a table for this.

**Comment by pld** [comment]
Let's also not do the maybe part of split by center and station.

@akahure did you talk w/the client about this?

**Comment by akahure** [comment]
@pld coincidentally we have a description of the _turnout report_ from the quarantine triggers shared, We have reviewed them with John and agreed to create issues around them. Though to answer the question above they confirmed this is the turnout reporting scope 

![Screenshot 2020-04-17 at 14 54 29](https://user-images.githubusercontent.com/43808025/79566525-5d40f800-80bb-11ea-8198-5b3e648a3c73.png)

So it works out the same way we had described it, we probably need clarification on what _`Province`_ is not sure I have seen this before, which could mean we need to accommodate more admin boundaries or match them to the current centres we have

**Comment by JohnMwashuma** [comment]
> Male/Female voters can be retrieved based on the station gender which specifies the gender that should vote in a particular station.

**Comment by JohnMwashuma** [comment]
> From the meeting we had, we agreed we will be using `office` in place of `province`, they said a `province` is a region which we do not have in the system.

**Comment by JohnMwashuma** [comment]
We need more information on this requirement, specifically the regions (West, Southwest and East):
 - What will these regions be tied to in the system, i.e. will they be tied to stations, centers e.t.c.

**Comment by akahure** [comment]
@JohnMwashuma as flagged in the responses, the client has requested that we include the other additional boundary levels i.e. Region, Constituency and Sub constituency 
I will also follow up and confirm what the relationship is like with other fields like Office/ Station 

@JohnMwashuma if you can please check on the effort to include _Region, Constituency and Sub constituency_ What is the impact in the system in the whole data collection process 
cc: @pld

**Comment by JohnMwashuma** [comment]
@akahure These are the issues that will implement Region and Constituency plus their relationship with the current modules in the system:
  - Add Constituency and regions csv files to the list of files that can be uploaded during tally creation #305
  - Create Constituency model #306
  - Create Regions Model #307

**Comment by akahure** [comment]
@JohnMwashuma how are we handling _Sub Constituencies_? 

Do we know if they are related to Constituencies, if they are we might need to request these lists from the HNEC since testing should be starting soon?

**Comment by pld** [comment]
Yea good question, that's never been entirely clear to me, I'd assume sub-consistencies make up constituencies, but it'd be good to get a well defined hierarchy of Regions, Offices, Constituencies, and Sub-Consistencies.

**Comment by JohnMwashuma** [comment]
@pld @akahure Good question, so Constituencies are not related to Sub Constituencies, at least that is what i got from the voter registration site https://test.libyavotes.ly/registration/subconstituencies/ that Ahmed provided.
From the site:
  - Regions have a one to many relationship with the Offices.
  - Constituencies have a one to many relationship with the Centers.

**Comment by JohnMwashuma** [comment]
The list of Sub Constituencies, Constituencies and Regions are also available on the site, we can download them in csv format and use them for testing.

**Comment by JohnMwashuma** [comment]
> ### Implementation plan:
> #### Turnout Report per Sub Constituency
> * For each `sub contituency`, use the `code` to get `results forms` associated with that `code`.
> * For each `result form`, get their `station` using `station number`.
> * Group the `result forms` by `station gender` and aggregate `number of registrants`, which will be `number of registrants` in the `sub contituency`.
> * For each `result form`, get the final `reconciliation form`.
> * For each `reconciliation form`, get the `number of ballots used`.
> * Aggregate the `number of ballots used`, this will be `number of ballots used` in the `sub contituency`, this will then translate to 1. `number of voters voted` in the `sub contituency`, 2.  `male voters or female voters` in the `sub contituency` depending on the `Station` gender.
> * The `number of registrants` which will translate to `number of voters` in the `sub contituency`.
> * The `number of voters` and `number of voters voted` will then be used to calculate the `turnout percentage` in the `sub contituency`.

@akahure And this is how we will handle Sub Constituencies turnout report.

**Comment by pld** [comment]
https://github.com/onaio/tally-ho/pull/314
