### ISSUE TITLE
Results Management System Reports

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#279]
### Current requirement functionality
---
*This functionality partially exists in the current software.*
### User Story
---
The Results Management system will produce a number of reports (including turnout reports, process progress reports and results) during the election results processing and can accommodate more than one election in no time. Below is a list of standard reports that could be included in the RMS system for tracking the process and final results.

1. Process Progress Report

   - Report of the Processed Polling Stations: Progressive report of the processed PS/PC will
be produced and should show the number of polling stations processed with PS/PC
identifying information (PC/PS codes etc.).

2. Turnout and Statistical

   - Turnout Reports per Constituency/Province/nation Wide: This report can be per
province/HNEC office, listing: total number of voters in the province, number of voters
voted, turnout percentage, male voters, female voters. https://github.com/onaio/tally-ho/issues/273
   - Summary of votes cast per administrative area and nationwide: The report may contain
the following information: number of valid votes, number of invalid votes, disqualified
votes. The report could be further broken down for reporting purposes (National,
Provincial, Constituency, HNEC office) https://github.com/onaio/tally-ho/issues/286

3. Progressive Reports
   - Report by candidate/list – Sorted by votes obtained: The report will list order of
candidates/list by vote. The report could contain; name and total votes obtained. The
report can be broken down to region, Constituency and sub constituency.
   - Report by ballot order: The report will contain all the candidates for the sub constituency. The report will be sorted as per the ballot paper appearance of
candidates.
   - Disqualified Stations/centres report with details
   - Winners by polling station: All candidates that obtained at least one vote in the polling
station will be included and sorted based on the number of votes obtained.
   - Winners by polling centre: All candidates that obtained at least one vote in the PC will
be included and sorted based on the number of votes obtained.

4. Process discrepancy reports
   - List of polling stations/centres under process audit (based on constituency/HNEC field
office/province)
   - List of polling station/centres under investigation &amp; field verification (based
constituency/HNEC field office/province)
   - List of polling stations/centres excluded after investigations (based constituency/HNEC
field office/province)

### Implementation
---
1. Process Progress Report: https://github.com/onaio/tally-ho/issues/280
   - Build out an overview table showing number of processed stations.
   - Build out a table showing each station details.

2. Turnout and Statistical https://github.com/onaio/tally-ho/issues/273
   - To be defined after the implementation questions are answered.

3. Progressive Reports
   - For Report by candidate/list: Build out a candidate votes report table that will show: number of votes per candidate and name. Sort this data by number of votes. https://github.com/onaio/tally-ho/issues/308
   - Report by ballot order:
     - Build out a table of candidates per sub constituency sorted by candidates ballot number. https://github.com/onaio/tally-ho/issues/284
   - Disqualified Stations/centres report with details:  (This is already available on the center and station list)
   - Winners by polling station: https://github.com/onaio/tally-ho/issues/282
     - Use the `station` model to build out a table for candidate votes list and sort by votes number. 
   - Winners by polling centre: https://github.com/onaio/tally-ho/issues/282
     - Use the `center` model to build out a table for candidate votes list and sort by votes number.

4. Process discrepancy reports: https://github.com/onaio/tally-ho/issues/303
   - For List of polling stations/centres under process audit:
      - Build out a list of polling stations/centres with result forms in audit state based on office.
   - For List of polling station/centres under investigation &amp; field verification (based
constituency/HNEC field office/province): Not clear at the moment.
   - For List of polling stations/centres excluded after investigations (based constituency/HNEC
field office/province): Not clear at the moment.

### Questions about each Implementation plan
---
1. Process Progress Report:
    - What will make a polling station processed? Maybe we check if all result forms for a particular polling station are in `ARCHIVED` state. No?

2. Turnout and Statistical
    - Define what a `province` is because currently we do not have that in the system.
    - How would we categorise male and female voters?
    - I would suggest we use a Station instead because we can get the `number of registrants` which will translate to `number of voters` in the Stations and the `number of ballots used` will translate to `number of voters voted`, using these we can then calculate the `turnout percentage`.
   - For  Summary of votes cast per administrative area and nationwide:
     - What makes disqualified votes? Is it the of number of cancelled ballots?
     - `The report could be further broken down for reporting purposes (National,
Provincial, Constituency, HNEC office)` Define `National, Provincial, and Constituency` here.

3. Progressive Reports
   - For Report by candidate/list:
      - `The report can be constituency or provincial-based and national for referendums` We need to know what constituency or provincial-based and national for referendums are here.
   - Report by ballot order: We need to define what `constituency/province` mean here.

4. Process discrepancy reports: 
   - For List of polling stations/centres under process audit  (based on constituency/HNEC field
office/province):
      - What do we mean by `(based on constituency/HNEC field office/province)`
   - For List of polling station/centres under investigation &amp; field verification (based
constituency/HNEC field office/province) and for List of polling stations/centres excluded after investigations (based constituency/HNEC field office/province):
      - What do we mean by polling station/centres under/after investigation and  (based constituency/HNEC field office/province).

### Related Issues:
---
https://github.com/onaio/tally-ho/issues/244

**Comment by JohnMwashuma** [comment]
@akahure Did we get answers from the client on for the above implementation questions?

**Comment by akahure** [comment]
Nothing yet, the meeting is tomorrow @JohnMwashuma

**Comment by JohnMwashuma** [comment]
From the meeting we had, we agreed we will be using `office` in place of `province`, they said a `province` is a region which we do not have in the system.

**Comment by JohnMwashuma** [comment]
Male/Female voters can be retrieved based on the station gender which specifies the gender that should vote in a particular station.

**Comment by akahure** [comment]
@JohnMwashuma I have added a couple of additional comments to the audit triggers and reports doc,

Turnout and Statistical 
Turnout Reports per Constituency/Province/nation Wide: This report can be per province/HNEC office, listing: total number of voters in the province, number of voters voted, turnout percentage, male voters, female voters.
- in this case, we agreed that province is a region, in which case there are three (West, Southwest and East)  - we do not have them in the system and possibly need to quantify the LOE before we can work on anything 

Summary of votes cast per administrative area and nationwide: The report may contain the following information: number of valid votes, number of invalid votes, disqualified votes. The report could be further broken down for reporting purposes (National, Provincial, Constituency, HNEC office)
- What are we defining as invalid votes and where do we capture them 
- What are reporting purposes since right now we have stations, sub cons, offices, voting districts how do these tie into the current structure?

Disqualified Stations/centres report with details
- Where is the source of this information and what is a disqualified station 

Winners by polling station: All candidates that obtained at least one vote in the polling station will be included and sorted based on the number of votes obtained.
- Also when do we declare a winner in a station, when the registered voters near to equal the number of ballots?

Process discrepancy reports
List of polling stations/centers under process audit (based on constituency/HNEC field office/province) - _New report? New process?_

**Comment by JohnMwashuma** [comment]
@akahure This means that the reports needing clarification have been blocked for now till we get clarification from the client. No?

For province's which a regions (West, Southwest and East) we need more information on this requirement, e.g. what will these regions be tied to in the system, i.e. will they be tied to stations, centers e.t.c. and then we can talk about the LOE of implementing this.

For the ```Also when do we declare a winner in a station, when the registered voters near to equal the number of ballots?.```
  - I think since this is a progressive report they only need to know who is the current winner at the moment but the winners will keep changing depending on the vote numbers overtime.
  - Also this requirement has already been implemented on this issue https://github.com/onaio/tally-ho/issues/282

For ```Where is the source of this information and what is a disqualified station``` do you think this could be the inactive stations?

**Comment by JohnMwashuma** [comment]
> Male/Female voters can be retrieved based on the station gender which specifies the gender that should vote in a particular station.

**Comment by pld** [comment]
https://github.com/onaio/tally-ho/pull/314
