### ISSUE TITLE
Create Polling Station Process Progress Report

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#280]
### User Story
---
Report of the Processed Polling Stations: Progressive report of the processed PS/PC will
be produced and should show the number of polling stations processed with PS/PC
identifying information (PC/PS codes etc.).

### Implementation plan
---
- [ ] Build out an overview table showing number of processed stations.

- [ ] Build out a table showing each station details

A polling station will be processed if all result forms for that polling station are in `ARCHIVED` state. @pld @akahure Please confirm if this is correct/makes sense.

### Related Issue(s)
---
https://github.com/onaio/tally-ho/issues/279

**Comment by akahure** [comment]
yes, Archived meaning they have gone through the whole process and been verified.

**Comment by JohnMwashuma** [comment]
@akahure Yes and the fields will be the station fields e.g. station number etc.
