### ISSUE TITLE
Indicative Triggers: blank ballots percentage trigger.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#300]
### User Story
---

The percentage of the blank ballots: if the percentage of the blank ballots exceeded a certain percentage (e.g. the blank ballots are more than %(?) of the ballots inside the ballot box).

Blank Ballots ≥ %(?)of the ballots inside the ballot box where Ballot inside the box = valid + invalid+ Unstamped/Called + blank

### Implementation
---

- Calculate the blank ballots percentage by dividing blank ballots number with number of ballots inside the box.
- Use the blank ballots trigger percentage value as the allowed blank ballots % of the ballots inside the ballot box.
- Compare the two values for minimal discrepancies.

**Comment by JohnMwashuma** [comment]
@pld @akahure Should we create `blank ballots` as a separate field on the `reconciliation form`?, currently this is combined with the invalid ballots [here](https://github.com/onaio/tally-ho/blob/ed22e3f7538cfc914a307ff53e258026e746a751/tally_ho/apps/tally/models/reconciliation_form.py#L43) and from this [doc](https://docs.google.com/document/d/15c5KBWE4Je3GR0t1yGx8tphqVWGexSmhW4l4U4o1FII/edit#) i see it being referred several times separately from the invalid ballots.

I think without separating this, the percentage of the blank ballots for this trigger will not work well currently because we can't separate invalid ballots from blank ballots at the moment.

**Comment by pld** [comment]
I think this'll depend in part on what the physical form looks like.

Those the physical form have a field for this?

**Comment by JohnMwashuma** [comment]
Makes sense, will ask this when we have a call with the client.

**Comment by JohnMwashuma** [comment]
Client has confirmed we can add an optional blank field on the recon form

**Comment by JohnMwashuma** [comment]
Related to: https://github.com/onaio/tally-ho/issues/245
