### ISSUE TITLE
Process discrepancy report: Create a List of polling stations and centers with forms in audit (based on region/ constituency/ sub constituency).

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#304]
Build a table of polling stations and centres with result forms in audit state (based on region/ constituency/ sub constituency)

**Comment by akahure** [comment]
@JohnMwashuma is this report not the same as http://tallyho.onalabs.org/super-administrator/form-audit/12/

**Comment by JohnMwashuma** [comment]
Based on this Doc:
```
This report should be based on (region/ constituency/ sub constituency). For example the first list will contains all stations/centres under audit in a particular sub constituency, the constituency list will contain all relevant stations/centres under its sub constituencies and the regional list will contain all relevant stations/centres under its constituencies.
```

**Comment by JohnMwashuma** [comment]
### Implementation plan
---

Process discrepancy report for Regions:
---
- Build out a list of regions and display the number of stations and centers with forms in audit state for each region.
- Make the region names clickable so that one can click and view the list of stations and centers with forms in audit state.

Process discrepancy report for Constituencies:
---
- Build out a list of constituencies and display the number of stations and centers with forms in audit state for each constituency.
- Make the constituency names clickable so that one can click and view the list of stations and centers with forms in audit state.
- On the stations and centers, also display the constituency region name.

Process discrepancy report for Sub Constituencies:
---
- Build out a list of sub constituencies and display the number of stations and centers with forms in audit state for each sub constituency.
- Make the sub constituency names clickable so that one can click and view the list of stations and centers with forms in audit state.
- On the stations and centers, also display the sub constituency constituency name and region name.
