### ISSUE TITLE
Progressive report: Create a Report by candidate/list

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#308]
### Current requirement functionality
---
*This functionality partially exists in the current software.*

### User story
---
Report by candidate/list – Sorted by votes obtained: The report will list order of
candidates/list by vote. The report could contain; name and total votes obtained. The
report can be region, Constituency and sub constituency.

### Implementation plan
---

#### Report by candidate/list per Region
- For each `region`, get the `offices` assigned to that particular `region`.
   - For each `office`, get `result forms` assigned to that particular `office`.
      - For each `result form`, get it's `candidates`.
         - For each `candidate`, get their `full name` and `number of valid votes`.
    - Aggregate the `number of valid votes` per `candidate` this will make up the total number of valid votes of a candidate per office.
- Aggregate the total number of valid votes of a candidate per office which will make up the votes summary per region. 

#### Report by candidate/list per Constituency
- For each `constituency`, get the `centers` assigned to that particular `constituency`.
   - For each `center`, get `result forms` assigned to that particular `center`.
      - For each `result form`, get it's `candidates`.
         - For each `candidate`, get their `full name` and `number of valid votes`.
    - Aggregate the `number of valid votes` per `candidate` this will make up the total number of valid votes of a candidate per center.
- Aggregate the total number of valid votes of a candidate per center which will make up the votes summary per constituency. 

#### Summary of votes cast per Sub Constituency
- For each `sub constituency`, use the `code` to get `results forms` assigned to it.
    - For each `result form`, get it's `candidates`.
         - For each `candidate`, get their `full name` and `number of valid votes`.
- Aggregate the `number of valid votes` per `candidate` this will make up the total number of valid votes of a candidate per sub constituency.

**Comment by JohnMwashuma** [comment]
Related to: https://github.com/onaio/tally-ho/issues/279

**Comment by pld** [comment]
https://github.com/onaio/tally-ho/pull/314
