### ISSUE TITLE
Fix loading of the final results presentation table.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#368]
### User story
---
Currently the results page displays an error pop up on initial load. This is because the request headers are big and gets dropped by Nginx and Uwsgi.

### Expected behavior
---
The page should render a table containing results of all candidates.

### Task check list
---
- [x] Bump up the default block size for uwsgi. Update this on the tallyho ansible role [here](https://github.com/onaio/ansible-tally-ho/blob/9167abcb2c69830e2dea6def98996b32334bd596/meta/main.yml#L18).
     - [x] Set the `django_wsgi_buffer_size` variable.

**Comment by faith-mutua** [comment]
@JohnMwashuma The issue has been resolved. The [form result](https://tallyho.onalabs.org/super-administrator/form-results/1/)s page now loads without any errors
