### ISSUE TITLE
Proposed ballots and sub constituency ballots csv file structure's

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#388]
### User story
---
Due to the need of the tally system to support dynamic ballot types, the current file structure that contains ballot types does not work well with this in mind. That said, a better file structure for ballot types and sub constituency ballots needs to be created so that it's a bit straight forward on how dynamic ballots will be added/removed during initial tally creation.

### Proposed ballots file structure
---
This file will be used for creating all electrol races and ballots. 
- [ ] A ballots csv file with be used to hold all the ballot types (electrol races) and numbers.
- [ ] This csv file will consist of the following columns:
    - type: for the ballot type (electrol race).
    - number: for the ballot number.
This  approach will mean that for scenario's where we have more than one ballot number assigned to the same ballot type, then the ballot type (electrol race) will appear more than once. However, this should not be an issue.

### Example ballots file structure
---
| type | number |
| -------- | -------- | 
| PRESIDENTIAL | 103 |
| GENERAL | 1 | 
| GENERAL | 2 | 
| WOMEN | 76 |
| COMPONENT_AMAZIGH | 54 |
| COMPONENT_TWARAG | 55 |
| COMPONENT_TWARAG | 57 |
| COMPONENT_TEBU | 56 |
| COMPONENT_TEBU | 58 |

### Proposed Sub Constituency Ballots file structure
---
This is a separate file from the main sub constituency file. It's main purpose is to show the mapping/assignments of ballots to sub constituencies. 
 - [ ] A sub constituency ballots csv file with be used to hold all the sub constituencies codes with their ballot number assignments.
 - [ ] This csv file will consist of the following columns:
    - code: for the sub constituency code.
    - number: for the ballot number.
    
This  approach will need good validation logic to validate that the sub constituency codes and ballot numbers are actually valid and do exist in the system. This also means we will do away with the ballot number columns in the main sub constituency file except for the number of ballots columns that is need to validate correct number of ballots have been assigned to a sub constituency.

### Example Sub Constituency Ballots file structure
---
| code | number |
| -------- | -------- | 
| 1 | 103 |
| 1 | 1 | 
| 2 | 103| 
| 2 | 2 |
| 2 | 76 |
| 3 | 103 |
| 3 | 3 |
| 3 | 77 |

### Related to:
---
https://github.com/onaio/tally-ho/issues/374

**Comment by mrajayp** [comment]
Thanks! 

So the ballot form, I might suggest having two catergories/levels. 
Level 1 - Election Level 
Level 2 - Sub-Type

Presidential / General / 
Presidential / Runoff /
HoR /  General
HoR / Women
HoR / Component_Amazigh
Senate /  General 
Senate / Women

**Comment by JohnMwashuma** [comment]
> Thanks!
> 
> So the ballot form, I might suggest having two catergories/levels. Level 1 - Election Level Level 2 - Sub-Type
> 
> Presidential / General / Presidential / Runoff / HoR / General HoR / Women HoR / Component_Amazigh Senate / General Senate / Women

Cool so in total we have 3 columns on the ballots file. We add an extra column called `sub_type` and rename the `type` column to `election_level`. So columns will be:
  - election_level
  - sub_type
  - number
 
That said, will that then mean for the Election Levels that have the same name e.g. `Presidential` will have unique ballot numbers?.
