### ISSUE TITLE
Fix applying corrections for boolean fields

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#419]
### Context
---
When a result form requires corrections due to discrepancies in DE1 and DE2 entries, applying corrections for boolean fields fails.

### Task check list
---
 - [x] Fix handle boolean fields when applying corrections in the corrections required view[ post method.](https://github.com/onaio/tally-ho/blob/5c53d8772392b8ea3b18176e94ccfeb54ca59e9a/tally_ho/apps/tally/views/corrections.py#L356)

**Comment by faith-mutua** [comment]
@lincmba @JohnMwashuma this issue has been resolved.
