### ISSUE TITLE
TallyHo Client Requests (Bugs/Enhancema: Form Revisions, Barcode Validation, Dashboard Errors, and Candidate Results

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#433]
# Bug Report: Tally Requests

### Description:
The form needs to be updated to match the revised reconciliation form.

### Proposed Changes:
- Remove blank ballots.
- Change the label "number of signatures" to "number of cards".

---

### Description:
The system currently allows the `results_forms` file, which contains duplicate barcodes, to be uploaded.

### Proposed Change:
- Add a validation check for duplicate barcodes during the `results_forms` file upload.

---

### Description:
When navigating to the Form List and selecting a stage, such as "intake", the following error can occur:

![image](https://github.com/user-attachments/assets/f60c8be9-667c-4a46-92d3-eb9507aed80a)

**URL:** [https://tallyho.onalabs.org/data/form-list/1/intake/](https://tallyho.onalabs.org/data/form-list/1/intake/)

### Proposed Change:
- Bug fix: Resolve the error that occurs when selecting a stage in the Form List.

---

### Description:
In the admin dashboard under "Download Results" >> "Candidate Results", the table does not include the Sub Constituency/Municipality name. Additionally, there is no option to filter by Sub Constituency/Municipality name.

**URL:** [https://tallyho.onalabs.org/super-administrator/form-results/1/](https://tallyho.onalabs.org/super-administrator/form-results/1/)

### Proposed Changes:
- Amend the filter and table to include the Sub Constituency/Municipality name.

**Comment by faith-mutua** [comment]
@JohnMwashuma all the issues raised above have been addressed.
